### ISSUE TITLE
Update to a standard licence

### ISSUE THREAD

**Issue by nick-cr** [NewChromantics/PopH264#23]
Very interested in integrating this into our project.

The licence makes this a little tricky however. We are happy with the terms of the licence but the fact it is non standard makes it harder for us to integrate.

Could we perhaps switch to one of the BSD licences as the terms look pretty similar to some of those license already? Alternatively MIT or Apache.

**Comment by SoylentGraham** [comment]
Switched to Mozilla Public License 2.0 from 2aab1cb3ec7389fcb9d90999b9cf84a9375d3f21
