### ISSUE TITLE
Memory leak on Windows

### ISSUE THREAD

**Issue by nick-cr** [NewChromantics/PopH264#37]
Steps to reproduce:

Either

1. On Windows create an instance of the decoder
2. Decode some frames
3. Get rid of the decoder with `Dispose()` or `PopH264_DestroyDecoder(Instance.Value);`
4. Repeat a few times

or

1. Add Mp4 to a scene with some content
2. Start the scene in the editor, wait for frames
3. Stop the scene in the editor
4. Repeat a few times

The memory is not cleared (which looks roughly equivalent to the buffered frames). If you create instances of players regularly and play relatively high definition video this is a very quick memory leak!

**Comment by SoylentGraham** [comment]
Most being freed now, a decoder can decode 10,000 frames and use the same amount of memory, but when the transformer/decoder is released, some memory still lingers around. (Broadway doesn't do this, so it's definitely something inside mediafoundation)

**Comment by SoylentGraham** [comment]
Fixed in 5770d4a7e9a4a0afddbec919235b6f892c2a806c
