### ISSUE TITLE
When android build fails, github action reports success

### ISSUE THREAD

**Issue by SoylentGraham** [NewChromantics/PopH264#39]
This includes the action's entrypoint.sh syntax errors.
(Maybe only the old @v1)

Lets FORCE an error if there are no .so's or some significant files in the output.

Artifact output is this (so there IS a file.... but probably not the one we want)
https://github.com/NewChromantics/PopH264/runs/1838584005?check_suite_focus=true
```With the provided path, there will be 1 file uploaded
Total size of all the files uploaded is 2827 bytes
Finished uploading artifact Android. Reported size is 2827 bytes. There were 0 items that failed to upload
Artifact Android has been successfully uploaded!```

**Comment by SoylentGraham** [comment]
Updated `create release` build with v2 d7ae00d5a3ed8a3dd64e3b0922c79f7b642528df but we should add some safety net

**Comment by thomasSDK** [comment]
Changed the Android action to use a bash script and added [Bash Error Handling](https://citizen428.net/blog/bash-error-handling-with-trap/) to exit if any errors are detected with

`set -Ee`
