### ISSUE TITLE
iOS binary not built with bitcode enabled

### ISSUE THREAD

**Issue by robcharlwood** [NewChromantics/PopH264#51]
We are currently trying to compile the iOS binary with XCode but it is complaining that the binary is not in bitcode format and so its failing to compile. I see from your GitHub action that the plugin is built with bitcode turned off. Is there a specific reason for this? If not, would it be possible to get a version of the iOS binary with bitcode enabled? Maybe as a separate artifact?

**Comment by robcharlwood** [comment]
I found this information in the latest Apple build github action log:

https://github.com/NewChromantics/PopH264/runs/2015562986?check_suite_focus=true

All the mentions of ``ENABLE_BITCODE`` are set  to ``NO``

**Comment by robcharlwood** [comment]
> #45 I enabled this recently... (I even pushed a version to testflight last night)
> 
> I'll double check today why that's off...
> 
> Are you building just the ios framework, or the universal framework? (not that it should be any different)

Thanks @SoylentGraham - We are downloading and utilizing the ios binaries from the ``PopH264.xcframework.zip`` archive for the relevant release (in our case - currently 1.3.29)

**Comment by SoylentGraham** [comment]
Aha!

bitcode IS enabled in the ios framework target, but the env var `BITCODE_ENABLED` is no by default for the universal build. (which is reported in the build)
The universal build isn't actually using this env var/build setting. (the universal build, builds the ios target, ios sim target, and mac target from CLI and then smushes them together into a shared framework)

If you get 1.3.30 (as per #45) I think the error will go away.
Maybe I should strip out all the build settings that I can from the `external build target`s (wasm, universal, android, linux)

**Comment by robcharlwood** [comment]
Thanks @SoylentGraham I will try upgrading! :sweat_smile:

**Comment by robcharlwood** [comment]
Thanks @SoylentGraham - this worked for us. :sweat_smile:
