### ISSUE TITLE
DLL not found on Mac OSX

### ISSUE THREAD

**Issue by nick-cr** [NewChromantics/PopH264#56]
We are having trouble getting the dll to be found on Mac. I see there is an issue relating to the face that  xcframework is corrupted here: https://github.com/NewChromantics/PopH264/issues/41. Could this be causing the plugin to fail?

Has this been tested on Mac? Are there any steps it is worth exploring to try to get this to work?

**Comment by SoylentGraham** [comment]
What error are you getting? (in what engine/loader)
It *probably* is just that the github-builds are not signed properly at the moment. 
I just downloaded the .tgz from the npm repository to use in unreal, but it's not signed so it won't load it.

I just built it myself (open xcodeproj and build) and used that.

**Comment by SoylentGraham** [comment]
`codesign -vvvv PopH264_Osx.framework` will verify that it's not signed, (or has been modified post-signing)

**Comment by tidus9000** [comment]
This is in the Unity plugin
running codesign got ``a sealed resource is missing or invalid`` so that's probably it, give building locally a go

**Comment by SoylentGraham** [comment]
```
PopH264.xcframework/macos-x86_64/PopH264_Osx.framework: a sealed resource is missing or invalid
file added: /Users/graham/Downloads/package 5/PopH264.xcframework/macos-x86_64/PopH264_Osx.framework/Versions/Current/_CodeSignature.meta
file added: /Users/graham/Downloads/package 5/PopH264.xcframework/macos-x86_64/PopH264_Osx.framework/Versions/Current/Resources/Info.plist.meta
file added: /Users/graham/Downloads/package 5/PopH264.xcframework/macos-x86_64/PopH264_Osx.framework/Versions/Current/Headers.meta
file added: /Users/graham/Downloads/package 5/PopH264.xcframework/macos-x86_64/PopH264_Osx.framework/Versions/Current/PopH264_Osx.meta
file added: /Users/graham/Downloads/package 5/PopH264.xcframework/macos-x86_64/PopH264_Osx.framework/Versions/Current/Resources.meta
file added: /Users/graham/Downloads/package 5/PopH264.xcframework/macos-x86_64/PopH264_Osx.framework/Versions/Current/Headers/PopH264.h.meta

```
Yeah, this error is that the .meta files have been added AFTER it's been signed (so seal is broken). 
We were definitely fixing this so we add the .meta files at build time... (pre-sign) but I think we had a few little issues with that... The unity setup (requiring .meta files) and building frameworks (can't have those .meta files present) conflicted with each other a bit.

As thomas said;
> For codesigning the mac framework it doesnt seem that we can add any extra files to the root of the framework.
But unity needs it.
It may be that using the `/Versions/A/` path (another thing that needs fixing as the symlinks are baked when publishing) is a work around

**Comment by SoylentGraham** [comment]
Perhaps the workaround is going all the way back to building a `.bundle`, just for unity & mac. (But I don't know if that's going to have the same codesigning issues)

**Comment by SoylentGraham** [comment]
Another possible mega hacky option, might be trying to find a way to bundle the whole signed .framework into a managed DLL, and see if unity/osx binary can load the framework from inside that. Then the DLL gets a single .meta and the framework doesn't need to be modified (and maybe that DLL can contain all-platforms too)

**Comment by tidus9000** [comment]
so I'm not sure if I'm doing anything wrong but I built PopH264 locally using the `PopH264_Universal` target in xcode, the resulting osx framework seems to import into a blank Unity project indefinitely (or at least for a very very long time).

**Comment by SoylentGraham** [comment]
Don't think I've seen anything where unity gets stuck forever adding a framework... try building just the mac target in xcode and dropping the new osx.framework overwriting the old one, and see if it's any different?

Although the .xcframework is signed, ios/osx/xcode/.app don't seem to be fussed if you modify its contents

What do you see when it takes forever, a loading dialog?

**Comment by SoylentGraham** [comment]
All fixed.
Mac switched to .dylib which unity works a lot nicer with.

All packaged in a unity-package now
https://github.com/NewChromantics/PopH264.UnityPackage
