### ISSUE TITLE
option to disable this!`)

### ISSUE THREAD

**Issue by bastivr8t54907zi690** [NewChromantics/PopH264#70]
https://github.com/NewChromantics/PopH264/blob/7a15be0e51c9ac192f12a93a49a82ebcd45518e6/Readme.md#L210-L211

**Comment by SoylentGraham** [comment]
Disable what?

webcodecs is now publically availible though, so you don't need to implement google/chrome's origin trial

Only working under https or localhost is a chrome restriction, nothing in this code

**Comment by SoylentGraham** [comment]
webcodecs is now enabled by default everywhere where secure (https and http).

Only real exception is IOS pre ios16 (eg. my iphone SE)
