### ISSUE TITLE
Unable to build UWP

### ISSUE THREAD

**Issue by LLS-Itzhakp** [NewChromantics/PopH264#72]
When trying to build UWP ARM or ARM64 there is a huge list of issues.

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "extraFlags.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\extraFlags.c	1	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_byte_stream.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cfg.h	35	
Error (active)	E1696	cannot open source file "opttarget.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_conceal.c	32	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_conceal.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_container.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_deblocking.c	50	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_deblocking.h	35	
Error (active)	E1696	cannot open source file "opttarget.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_decoder.c	41	
Error (active)	E1696	cannot open source file "extraFlags.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_decoder.c	42	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_decoder.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_dpb.c	61	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_dpb.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_image.h	35	
Error (active)	E1696	cannot open source file "opttarget.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_inter_prediction.c	38	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_inter_prediction.h	35	
Error (active)	E1696	cannot open source file "opttarget.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_intra_prediction.c	55	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_intra_prediction.h	35	
Error (active)	E1696	cannot open source file "opttarget.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_macroblock_layer.h	31	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_macroblock_layer.h	37	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_nal_unit.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_neighbour.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_pic_order_cnt.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_pic_param_set.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_reconstruct.c	33	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_reconstruct.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_seq_param_set.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_slice_data.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_slice_group_map.c	40	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_slice_group_map.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_slice_header.h	35	
Error (active)	E1696	cannot open source file "opttarget.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_storage.c	40	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_storage.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_stream.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_transform.c	36	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_transform.h	35	
Error (active)	E1696	cannot open source file "H264SwDecApi.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_util.h	39	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_util.h	46	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_vlc.c	38	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_vlc.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_vui.c	36	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_vui.h	35	
Error (active)	E1696	cannot open source file "basetype.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\H264SwDecApi.c	40	
Error (active)	E1696	cannot open source file "H264SwDecApi.h"	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\H264SwDecApi.c	42	
Error (active)	E0020	identifier "u32" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_byte_stream.c	80	
Error (active)	E0020	identifier "u8" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_byte_stream.c	80	
Error (active)	E0020	identifier "u32" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_byte_stream.c	80	
Error (active)	E0020	identifier "u32" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_byte_stream.c	81	
Error (active)	E0020	identifier "u32" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_byte_stream.h	50	
Error (active)	E0020	identifier "u8" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_byte_stream.h	50	
Error (active)	E0020	identifier "u32" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_byte_stream.h	50	
Error (active)	E0020	identifier "u32" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_byte_stream.h	51	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	78	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	85	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	94	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	104	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	111	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	118	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	125	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	144	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	155	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	174	
Error (active)	E0020	identifier "u16" is undefined	PopH264.Uwp	C:\work\PopH264\Source\Broadway\Decoder\src\h264bsd_cavlc.c	185

**Comment by SoylentGraham** [comment]
UWP now built for x64, arm and arm64.

Builds integrated into unity via package manager; https://github.com/NewChromantics/PopH264.UnityPackage
